from PyQt5 import QtCore, QtGui, QtWidgets
import time

# 음료, 음료의 가격 정의
# 금액 변수 초기화

drinkList = ['아이시스', '아이시스', '아이시스', '레몬워터', '레몬워터', '옥수수\n수염차', '옥수수\n수염차', '콘트라\n베이스', '트레비', '트레비',
             '밀키스', '펩시', '핫식스', '칠성사이다', '코코리치', '코코리치', '립톤복숭아', '트로피카나\n사과맛', '트로피카나\n사과맛', '트로피카나\n포도맛',
             '가나초코', '가나초코', '레쓰비', '레쓰비', '칸타타', '레쓰비\n카페타임', '게토레이', '게토레이', '코코포도', '잔치집식혜']
moneyList = [700, 700, 700, 1600, 1600, 1400, 1400, 2100, 1100, 1100,
             900, 900, 1100, 1100, 1100, 1100, 1100, 1100, 1100, 1100,
             700, 700, 700, 700, 1100, 1100, 900, 900, 900, 900]

money = 0

class Ui_MainWindow(object):
    
    #class myMoney(self):
    
    # 자판기 프로세스 초기화

    def initialize(self):
        self.numDisplay.display(123456)
        self.drinkGroup.setEnabled(False) # 음료 선택 불가
        self.drinkBox.setText("") 
        self.drinkBox.setText("판매중") # 판매중 글자 띄우기
        self.drinkBox.setEnabled(True)
        self.releaseButton.setEnabled(False)

        for i in range(30):
            drinkLabel = drinkList[i] + "\n" + str(moneyList[i]) + "원" # 리스트의 값을 자판기 창의 각 라벨에 대입
            exec(f"self.drink{i}.setText(drinkLabel)")
    
    # 남은 돈이 없거나, 반환을 누름으로 인해 판매 작업을 종료하는 함수

    def getBack(self):
        self.drinkBox.append("이용해 주셔서 감사합니다.")
        self.numDisplay.display(123456)
        self.drinkGroup.setEnabled(False)
        self.releaseButton.setEnabled(False)

    # 돈을 넣음으로써 호출되는 함수

    def inputMoney(self, addedmoney):
        global money
        money += addedmoney
        self.gotMoney()

    # 사용자가 넣은 돈을 자판기가 추가하는 함수

    def gotMoney(self):
        global money
        self.numDisplay.display(money)
        self.drinkGroup.setEnabled(True)
        self.releaseButton.setEnabled(True)
        self.compareMoney()

    # 자판기에 들어온 돈과 각 음료의 가격을 비교하고, 구매할 수 있는 음료 아래 버튼에 ◉ 표시로 강조하는 함수

    def compareMoney(self):
        global money
        for i in range(30):
            if money >= moneyList[i]:
                exec(f"self.buy{i}.setText('구매 (◉)')")
            else:
                exec(f"self.buy{i}.setText('구매')")


    # 음료의 구매 버튼을 누르면 출력되는 함수

    def buyDrink(self, _int):
        global money
        if money >= moneyList[_int]:
            money -= moneyList[_int]
            self.numDisplay.display(money)
            self.drinkBox.append(f"{drinkList[_int]}를 구매하였습니다.")
            self.compareMoney()
        else:
            self.drinkBox.append("잔액이 부족합니다.")
        if money == 0:
            self.getBack()

    
    # 반환 버튼을 누르면 호출되는 함수
    
    def releaseMoney(self):
        global money
        money = 0
        self.numDisplay.display(0)
        self.getBack()

    # GUI 구성


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drinkGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.drinkGroup.setGeometry(QtCore.QRect(20, 10, 1051, 551))
        self.drinkGroup.setObjectName("drinkGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.drinkGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 1042, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drink0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink0.setObjectName("drink0")
        self.verticalLayout_2.addWidget(self.drink0)
        self.buy0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy0.setObjectName("buy0")
        self.verticalLayout_2.addWidget(self.buy0)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.drink1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink1.setObjectName("drink1")
        self.verticalLayout_23.addWidget(self.drink1)
        self.buy1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy1.setObjectName("buy1")
        self.verticalLayout_23.addWidget(self.buy1)
        self.gridLayout.addLayout(self.verticalLayout_23, 0, 1, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.drink2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink2.setObjectName("drink2")
        self.verticalLayout_24.addWidget(self.drink2)
        self.buy2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy2.setObjectName("buy2")
        self.verticalLayout_24.addWidget(self.buy2)
        self.gridLayout.addLayout(self.verticalLayout_24, 0, 2, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.drink4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink4.setObjectName("drink4")
        self.verticalLayout_26.addWidget(self.drink4)
        self.buy4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy4.setObjectName("buy4")
        self.verticalLayout_26.addWidget(self.buy4)
        self.gridLayout.addLayout(self.verticalLayout_26, 0, 4, 1, 1)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.drink3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink3.setObjectName("drink3")
        self.verticalLayout_25.addWidget(self.drink3)
        self.buy3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy3.setObjectName("buy3")
        self.verticalLayout_25.addWidget(self.buy3)
        self.gridLayout.addLayout(self.verticalLayout_25, 0, 3, 1, 1)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.drink5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink5.setObjectName("drink5")
        self.verticalLayout_27.addWidget(self.drink5)
        self.buy5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy5.setObjectName("buy5")
        self.verticalLayout_27.addWidget(self.buy5)
        self.gridLayout.addLayout(self.verticalLayout_27, 0, 5, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.drink8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink8.setObjectName("drink8")
        self.verticalLayout_30.addWidget(self.drink8)
        self.buy8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy8.setObjectName("buy8")
        self.verticalLayout_30.addWidget(self.buy8)
        self.gridLayout.addLayout(self.verticalLayout_30, 0, 8, 1, 1)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.drink7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink7.setObjectName("drink7")
        self.verticalLayout_29.addWidget(self.drink7)
        self.buy7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy7.setObjectName("buy7")
        self.verticalLayout_29.addWidget(self.buy7)
        self.gridLayout.addLayout(self.verticalLayout_29, 0, 7, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.drink6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink6.setObjectName("drink6")
        self.verticalLayout_28.addWidget(self.drink6)
        self.buy6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy6.setObjectName("buy6")
        self.verticalLayout_28.addWidget(self.buy6)
        self.gridLayout.addLayout(self.verticalLayout_28, 0, 6, 1, 1)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.drink9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink9.setObjectName("drink9")
        self.verticalLayout_31.addWidget(self.drink9)
        self.buy9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy9.setObjectName("buy9")
        self.verticalLayout_31.addWidget(self.buy9)
        self.gridLayout.addLayout(self.verticalLayout_31, 0, 9, 1, 1)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.drink10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink10.setObjectName("drink10")
        self.verticalLayout_32.addWidget(self.drink10)
        self.buy10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy10.setObjectName("buy10")
        self.verticalLayout_32.addWidget(self.buy10)
        self.gridLayout.addLayout(self.verticalLayout_32, 1, 0, 1, 1)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.drink20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink20.setObjectName("drink20")
        self.verticalLayout_33.addWidget(self.drink20)
        self.buy20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy20.setObjectName("buy20")
        self.verticalLayout_33.addWidget(self.buy20)
        self.gridLayout.addLayout(self.verticalLayout_33, 2, 0, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.drink11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink11.setObjectName("drink11")
        self.verticalLayout_34.addWidget(self.drink11)
        self.buy11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy11.setObjectName("buy11")
        self.verticalLayout_34.addWidget(self.buy11)
        self.gridLayout.addLayout(self.verticalLayout_34, 1, 1, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.drink21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink21.setObjectName("drink21")
        self.verticalLayout_35.addWidget(self.drink21)
        self.buy21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy21.setObjectName("buy21")
        self.verticalLayout_35.addWidget(self.buy21)
        self.gridLayout.addLayout(self.verticalLayout_35, 2, 1, 1, 1)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.drink12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink12.setObjectName("drink12")
        self.verticalLayout_36.addWidget(self.drink12)
        self.buy12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy12.setObjectName("buy12")
        self.verticalLayout_36.addWidget(self.buy12)
        self.gridLayout.addLayout(self.verticalLayout_36, 1, 2, 1, 1)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.drink22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink22.setObjectName("drink22")
        self.verticalLayout_37.addWidget(self.drink22)
        self.buy22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy22.setObjectName("buy22")
        self.verticalLayout_37.addWidget(self.buy22)
        self.gridLayout.addLayout(self.verticalLayout_37, 2, 2, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.drink13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink13.setObjectName("drink13")
        self.verticalLayout_38.addWidget(self.drink13)
        self.buy13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy13.setObjectName("buy13")
        self.verticalLayout_38.addWidget(self.buy13)
        self.gridLayout.addLayout(self.verticalLayout_38, 1, 3, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.drink14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink14.setObjectName("drink14")
        self.verticalLayout_39.addWidget(self.drink14)
        self.buy14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy14.setObjectName("buy14")
        self.verticalLayout_39.addWidget(self.buy14)
        self.gridLayout.addLayout(self.verticalLayout_39, 1, 4, 1, 1)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.drink15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink15.setObjectName("drink15")
        self.verticalLayout_40.addWidget(self.drink15)
        self.buy15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy15.setObjectName("buy15")
        self.verticalLayout_40.addWidget(self.buy15)
        self.gridLayout.addLayout(self.verticalLayout_40, 1, 5, 1, 1)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.drink16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink16.setObjectName("drink16")
        self.verticalLayout_41.addWidget(self.drink16)
        self.buy16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy16.setObjectName("buy16")
        self.verticalLayout_41.addWidget(self.buy16)
        self.gridLayout.addLayout(self.verticalLayout_41, 1, 6, 1, 1)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.drink17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink17.setObjectName("drink17")
        self.verticalLayout_42.addWidget(self.drink17)
        self.buy17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy17.setObjectName("buy17")
        self.verticalLayout_42.addWidget(self.buy17)
        self.gridLayout.addLayout(self.verticalLayout_42, 1, 7, 1, 1)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.drink23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink23.setObjectName("drink23")
        self.verticalLayout_43.addWidget(self.drink23)
        self.buy23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy23.setObjectName("buy23")
        self.verticalLayout_43.addWidget(self.buy23)
        self.gridLayout.addLayout(self.verticalLayout_43, 2, 3, 1, 1)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.drink24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink24.setObjectName("drink24")
        self.verticalLayout_44.addWidget(self.drink24)
        self.buy24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy24.setObjectName("buy24")
        self.verticalLayout_44.addWidget(self.buy24)
        self.gridLayout.addLayout(self.verticalLayout_44, 2, 4, 1, 1)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.drink25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink25.setObjectName("drink25")
        self.verticalLayout_45.addWidget(self.drink25)
        self.buy25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy25.setObjectName("buy25")
        self.verticalLayout_45.addWidget(self.buy25)
        self.gridLayout.addLayout(self.verticalLayout_45, 2, 5, 1, 1)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.drink26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink26.setObjectName("drink26")
        self.verticalLayout_46.addWidget(self.drink26)
        self.buy26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy26.setObjectName("buy26")
        self.verticalLayout_46.addWidget(self.buy26)
        self.gridLayout.addLayout(self.verticalLayout_46, 2, 6, 1, 1)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.drink27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink27.setObjectName("drink27")
        self.verticalLayout_47.addWidget(self.drink27)
        self.buy27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy27.setObjectName("buy27")
        self.verticalLayout_47.addWidget(self.buy27)
        self.gridLayout.addLayout(self.verticalLayout_47, 2, 7, 1, 1)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.drink18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink18.setObjectName("drink18")
        self.verticalLayout_48.addWidget(self.drink18)
        self.buy18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy18.setObjectName("buy18")
        self.verticalLayout_48.addWidget(self.buy18)
        self.gridLayout.addLayout(self.verticalLayout_48, 1, 8, 1, 1)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.drink19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink19.setObjectName("drink19")
        self.verticalLayout_49.addWidget(self.drink19)
        self.buy19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy19.setObjectName("buy19")
        self.verticalLayout_49.addWidget(self.buy19)
        self.gridLayout.addLayout(self.verticalLayout_49, 1, 9, 1, 1)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.drink28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink28.setObjectName("drink28")
        self.verticalLayout_51.addWidget(self.drink28)
        self.buy28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy28.setObjectName("buy28")
        self.verticalLayout_51.addWidget(self.buy28)
        self.gridLayout.addLayout(self.verticalLayout_51, 2, 8, 1, 1)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.drink29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.drink29.setObjectName("drink29")
        self.verticalLayout_52.addWidget(self.drink29)
        self.buy29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy29.setObjectName("buy29")
        self.verticalLayout_52.addWidget(self.buy29)
        self.gridLayout.addLayout(self.verticalLayout_52, 2, 9, 1, 1)
        self.drinkBox = QtWidgets.QTextEdit(self.centralwidget)
        self.drinkBox.setEnabled(False)
        self.drinkBox.setGeometry(QtCore.QRect(20, 570, 511, 141))
        self.drinkBox.setObjectName("drinkBox")
        self.numDisplay = QtWidgets.QLCDNumber(self.centralwidget)
        self.numDisplay.setGeometry(QtCore.QRect(670, 590, 191, 51))
        self.numDisplay.setObjectName("numDisplay")
        self.smallButton = QtWidgets.QPushButton(self.centralwidget)
        self.smallButton.setGeometry(QtCore.QRect(890, 570, 151, 41))
        self.smallButton.setObjectName("smallButton")
        self.medButton = QtWidgets.QPushButton(self.centralwidget)
        self.medButton.setGeometry(QtCore.QRect(890, 620, 151, 41))
        self.medButton.setObjectName("medButton")
        self.bigButton = QtWidgets.QPushButton(self.centralwidget)
        self.bigButton.setGeometry(QtCore.QRect(890, 670, 151, 41))
        self.bigButton.setObjectName("bigButton")
        self.releaseButton = QtWidgets.QPushButton(self.centralwidget)
        self.releaseButton.setGeometry(QtCore.QRect(670, 650, 191, 51))
        self.releaseButton.setObjectName("releaseButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # dynamic language switching을 하기 위한 함수

    def retranslateUi(self, MainWindow):
    
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zha Phan Ghi"))
        self.drinkGroup.setTitle(_translate("MainWindow", "LOTTE E&&M"))
        self.drink0.setText(_translate("MainWindow", "----"))
        self.buy0.setText(_translate("MainWindow", "구매"))
        self.drink1.setText(_translate("MainWindow", "----"))
        self.buy1.setText(_translate("MainWindow", "구매"))
        self.drink2.setText(_translate("MainWindow", "----"))
        self.buy2.setText(_translate("MainWindow", "구매"))
        self.drink4.setText(_translate("MainWindow", "----"))
        self.buy4.setText(_translate("MainWindow", "구매"))
        self.drink3.setText(_translate("MainWindow", "----"))
        self.buy3.setText(_translate("MainWindow", "구매"))
        self.drink5.setText(_translate("MainWindow", "----"))
        self.buy5.setText(_translate("MainWindow", "구매"))
        self.drink8.setText(_translate("MainWindow", "----"))
        self.buy8.setText(_translate("MainWindow", "구매"))
        self.drink7.setText(_translate("MainWindow", "----"))
        self.buy7.setText(_translate("MainWindow", "구매"))
        self.drink6.setText(_translate("MainWindow", "----"))
        self.buy6.setText(_translate("MainWindow", "구매"))
        self.drink9.setText(_translate("MainWindow", "----"))
        self.buy9.setText(_translate("MainWindow", "구매"))
        self.drink10.setText(_translate("MainWindow", "----"))
        self.buy10.setText(_translate("MainWindow", "구매"))
        self.drink20.setText(_translate("MainWindow", "----"))
        self.buy20.setText(_translate("MainWindow", "구매"))
        self.drink11.setText(_translate("MainWindow", "----"))
        self.buy11.setText(_translate("MainWindow", "구매"))
        self.drink21.setText(_translate("MainWindow", "----"))
        self.buy21.setText(_translate("MainWindow", "구매"))
        self.drink12.setText(_translate("MainWindow", "----"))
        self.buy12.setText(_translate("MainWindow", "구매"))
        self.drink22.setText(_translate("MainWindow", "----"))
        self.buy22.setText(_translate("MainWindow", "구매"))
        self.drink13.setText(_translate("MainWindow", "----"))
        self.buy13.setText(_translate("MainWindow", "구매"))
        self.drink14.setText(_translate("MainWindow", "----"))
        self.buy14.setText(_translate("MainWindow", "구매"))
        self.drink15.setText(_translate("MainWindow", "----"))
        self.buy15.setText(_translate("MainWindow", "구매"))
        self.drink16.setText(_translate("MainWindow", "----"))
        self.buy16.setText(_translate("MainWindow", "구매"))
        self.drink17.setText(_translate("MainWindow", "----"))
        self.buy17.setText(_translate("MainWindow", "구매"))
        self.drink23.setText(_translate("MainWindow", "----"))
        self.buy23.setText(_translate("MainWindow", "구매"))
        self.drink24.setText(_translate("MainWindow", "----"))
        self.buy24.setText(_translate("MainWindow", "구매"))
        self.drink25.setText(_translate("MainWindow", "----"))
        self.buy25.setText(_translate("MainWindow", "구매"))
        self.drink26.setText(_translate("MainWindow", "----"))
        self.buy26.setText(_translate("MainWindow", "구매"))
        self.drink27.setText(_translate("MainWindow", "----"))
        self.buy27.setText(_translate("MainWindow", "구매"))
        self.drink18.setText(_translate("MainWindow", "----"))
        self.buy18.setText(_translate("MainWindow", "구매"))
        self.drink19.setText(_translate("MainWindow", "----"))
        self.buy19.setText(_translate("MainWindow", "구매"))
        self.drink28.setText(_translate("MainWindow", "----"))
        self.buy28.setText(_translate("MainWindow", "구매"))
        self.drink29.setText(_translate("MainWindow", "----"))
        self.buy29.setText(_translate("MainWindow", "구매"))
        self.smallButton.setText(_translate("MainWindow", "\\100"))
        self.medButton.setText(_translate("MainWindow", "\\500"))
        self.bigButton.setText(_translate("MainWindow", "\\1000"))
        self.releaseButton.setText(_translate("MainWindow", "반환"))

        self.smallButton.clicked.connect(lambda : self.inputMoney(100))
        self.medButton.clicked.connect(lambda : self.inputMoney(500))
        self.bigButton.clicked.connect(lambda : self.inputMoney(1000))
        self.releaseButton.clicked.connect(lambda : self.releaseMoney())

        self.buy0.clicked.connect(lambda : self.buyDrink(0))
        self.buy1.clicked.connect(lambda : self.buyDrink(1))
        self.buy2.clicked.connect(lambda : self.buyDrink(2))
        self.buy3.clicked.connect(lambda : self.buyDrink(3))
        self.buy4.clicked.connect(lambda : self.buyDrink(4))
        self.buy5.clicked.connect(lambda : self.buyDrink(5))
        self.buy6.clicked.connect(lambda : self.buyDrink(6))
        self.buy7.clicked.connect(lambda : self.buyDrink(7))
        self.buy8.clicked.connect(lambda : self.buyDrink(8))
        self.buy9.clicked.connect(lambda : self.buyDrink(9))
        self.buy10.clicked.connect(lambda : self.buyDrink(10))
        self.buy11.clicked.connect(lambda : self.buyDrink(11))
        self.buy12.clicked.connect(lambda : self.buyDrink(12))
        self.buy13.clicked.connect(lambda : self.buyDrink(13))
        self.buy14.clicked.connect(lambda : self.buyDrink(14))
        self.buy15.clicked.connect(lambda : self.buyDrink(15))
        self.buy16.clicked.connect(lambda : self.buyDrink(16))
        self.buy17.clicked.connect(lambda : self.buyDrink(17))
        self.buy18.clicked.connect(lambda : self.buyDrink(18))
        self.buy19.clicked.connect(lambda : self.buyDrink(19))
        self.buy20.clicked.connect(lambda : self.buyDrink(20))
        self.buy21.clicked.connect(lambda : self.buyDrink(21))
        self.buy22.clicked.connect(lambda : self.buyDrink(22))
        self.buy23.clicked.connect(lambda : self.buyDrink(23))
        self.buy24.clicked.connect(lambda : self.buyDrink(24))
        self.buy25.clicked.connect(lambda : self.buyDrink(25))
        self.buy26.clicked.connect(lambda : self.buyDrink(26))
        self.buy27.clicked.connect(lambda : self.buyDrink(27))
        self.buy28.clicked.connect(lambda : self.buyDrink(28))
        self.buy29.clicked.connect(lambda : self.buyDrink(29))


# 직접 파일이 불러와진 경우에

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.initialize()
    time.sleep(0.4)
    sys.exit(app.exec_())

